export const APP_MENU_ACTIONS = {
  cut: "edit:cut",
  cutValues: "edit:cut-values",
  copy: "edit:copy",
  copyValues: "edit:copy-values",
  redo: "edit:redo",
  undo: "edit:undo",
  addColumn: "sheet:add-column",
  addRow: "sheet:add-row",
  deleteSelection: "edit:delete-selection",
  deleteSheet: "sheet:delete-sheet",
  exportCsv: "csv:export",
  importCsv: "csv:import",
  insertChart: "insert:chart",
  insertTable: "insert:table",
  deleteTable: "table:delete",
  newSheet: "sheet:new-sheet",
  openWorkbook: "workbook:open",
  paste: "edit:paste",
  pasteValues: "edit:paste-values",
  renameSheet: "sheet:rename-sheet",
  formatCells: "edit:format-cells",
  clearFormatting: "edit:clear-formatting",
  saveWorkbook: "workbook:save",
  saveWorkbookAs: "workbook:save-as",
  sortTableAscending: "table:sort-ascending",
  sortTableDescending: "table:sort-descending",
} as const;

export type AppMenuAction = (typeof APP_MENU_ACTIONS)[keyof typeof APP_MENU_ACTIONS];
